webtalk_init -webtalk_dir F:\\DMD_Projects\\project_3\\project_3.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-12-11 09:46:28" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "tnltn3mo2r78coqb7ik1i2df33" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.459 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1544512352931" -context "sdk\\\\bsp/1544512352931"
webtalk_add_data -client sdk -key hwid -value "1542706101262" -context "sdk\\\\bsp/1544512352931"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1544512352931"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\bsp/1544512352931"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1544512352931"
webtalk_add_data -client sdk -key uid -value "1544512358763" -context "sdk\\\\application/1544512358763"
webtalk_add_data -client sdk -key hwid -value "1542706101262" -context "sdk\\\\application/1544512358763"
webtalk_add_data -client sdk -key bspid -value "1544512352931" -context "sdk\\\\application/1544512358763"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1544512358763"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1544512358763"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\application/1544512358763"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1544512358763"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1544512358763"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1544512358763"
webtalk_add_data -client sdk -key projSize -value "168.46875" -context "sdk\\\\application/1544512358763"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1544514388327"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1544514388327"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1544514388327"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1544514388327"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1544514388327"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1544514388327"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1544514388327"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1544514388327"
webtalk_transmit -clientid 3593924329 -regid "" -xml F:\\DMD_Projects\\project_3\\project_3.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html F:\\DMD_Projects\\project_3\\project_3.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm F:\\DMD_Projects\\project_3\\project_3.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
